/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Clases.GenericaDb;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Alice
 */
public class frmVista extends javax.swing.JFrame {

    /**
     * Creates new form frmVista
     */
    int cont = 0;
    String nombre = "HJAMS";
    String apellido = "Inserccion";
    double Tinicio, Tfin, Tiempo;

    public frmVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn100mil = new javax.swing.JButton();
        btnBorrarDatos = new javax.swing.JButton();
        lblTiempo = new javax.swing.JLabel();
        lblInsert = new javax.swing.JLabel();
        lblTiempo1 = new javax.swing.JLabel();
        cmbNumDatos = new javax.swing.JComboBox<>();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn100mil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-añadir-a-la-base-de-datos-50.png"))); // NOI18N
        btn100mil.setText("Insert");
        btn100mil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn100mil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn100mil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn100mil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100milActionPerformed(evt);
            }
        });
        jPanel1.add(btn100mil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 27, 90, 80));

        btnBorrarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-base-de-datos-50.png"))); // NOI18N
        btnBorrarDatos.setText("Delete");
        btnBorrarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarDatos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBorrarDatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBorrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 27, 90, 80));

        lblTiempo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTiempo.setText("Tiempo de Ejecución:0");
        jPanel1.add(lblTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 200, 30));

        lblInsert.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblInsert.setText("Insercción:0");
        jPanel1.add(lblInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 130, 30));

        lblTiempo1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTiempo1.setText("Registros a Insertar:");
        jPanel1.add(lblTiempo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, 30));

        cmbNumDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10000", "50000", "100000" }));
        jPanel1.add(cmbNumDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 160, 30));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga.png"))); // NOI18N
        jPanel1.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarDatosActionPerformed
        // TODO add your handling code here:
        Statement declaracion = null;
        ResultSet resultado = null; //Obtner el resultado de dicha declaracion
        GenericaDb con = new GenericaDb();
        try //Se utiliza un try catch por si hay algun error a la ahora de hacer la conexion
        {
            declaracion = con.getConexion().createStatement();
            resultado = declaracion.executeQuery("Delete * from data");//hago la consulta y guardo     lo ontenido en resultado
            con.CerrarConexion();
            if (resultado.getInt(0)==1) {
                JOptionPane.showMessageDialog(null,"Delete Complet");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(getParent(), e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);//;Imprimo el error en un JoptinPane para mostrar el error
        }
    }//GEN-LAST:event_btnBorrarDatosActionPerformed

    private void btn100milActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100milActionPerformed
        // TODO add your handling code here:
        cont = 0;
        insertarDatos(cont, Integer.parseInt(cmbNumDatos.getItemAt(cmbNumDatos.getSelectedIndex())));
    }//GEN-LAST:event_btn100milActionPerformed

    public void insertarDatos(int cont, int numDatos) {
        Statement declaracion = null; //Realizar las declraciones de SQL
        ResultSet resultado = null; //Obtner el resultado de dicha declaracion
        GenericaDb con = new GenericaDb();
        Tinicio = System.currentTimeMillis();
        while (cont < numDatos) {
//            System.out.println("Insercción: " + (cont + 1));
            try //Se utiliza un try catch por si hay algun error a la ahora de hacer la conexion
            {
                declaracion = con.getConexion().createStatement();
                declaracion.executeQuery("INSERT INTO data (id,nombre,apellido) VALUES ('" + (cont + 1) + "','Name +" + cont + "','apellido +" + cont + "')");
                resultado = declaracion.executeQuery("SELECT COUNT(*) FROM data");//hago la consulta y guardo     lo ontenido en resultado
                con.CerrarConexion();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(getParent(), e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);//;Imprimo el error en un JoptinPane para mostrar el error
            }
            cont = cont + 1;
        }
        Tfin = System.currentTimeMillis();
        Tiempo = Tfin - Tinicio;
        lblTiempo.setText(Double.toString(Tiempo/1000));
        lblInsert.setText("Insercción:"+String.valueOf(numInserciones()));
        
    }

    public int numInserciones(){
        Statement declaracion = null;
        ResultSet resultado = null; //Obtner el resultado de dicha declaracion
        GenericaDb con = new GenericaDb();
        try //Se utiliza un try catch por si hay algun error a la ahora de hacer la conexion
        {
            declaracion = con.getConexion().createStatement();
            resultado = declaracion.executeQuery("SELECT COUNT(*) FROM data");//hago la consulta y guardo     lo ontenido en resultado
            con.CerrarConexion();
            return resultado.getInt(0);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(getParent(), e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);//;Imprimo el error en un JoptinPane para mostrar el error
            return 0;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100mil;
    private javax.swing.JButton btnBorrarDatos;
    private javax.swing.JComboBox<String> cmbNumDatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInsert;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTiempo1;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
